### ISSUE TITLE
bug minus ID glitch

### ISSUE THREAD

**Issue by SamuelGee** [chrrel/youtube-playlist-exporter#1]
Hi chrrel, thank you for sharing this wonderful tool.  I've just backed up my 150 playlists in 2 batches.
Me reporting some bug, seems like video IDs starting with minus sign are not processed correctly, script is putting space to the beginning.

https://www.youtube.com/watch?v=-UGmleOV42Y

![image](https://user-images.githubusercontent.com/8607953/189949762-8d7aeca1-da14-4842-b846-a473e8ec3590.png)

**Comment by chrrel** [comment]
Hey, 
thank you for pointing out this problem. Unfortunately, I cannot reproduce this issue. 

When using the following input file, no error occurs for me.

```
Playlist-ID,Kanal-ID,Zeitpunkt der Erstellung,Zeitpunkt der Aktualisierung,Titel,Beschreibung,Sichtbarkeit
ABCdEFgzFv5m_8-f3BJ0p1l-Dz12345678,abcdefghijklmnop,2020-01-05 01:02:03 UTC,2020-01-08 01:02:03 UTC,My Music,,Privat

Video-ID,Zeitpunkt des Hinzufügens
-UGmleOV42Y,2020-01-05 10:01:47 UTC
```

**Comment by chrrel** [comment]
Hi @SamuelGee, can you provide further data on this error, e.g more detailed logs or a stack trace? Maybe you could check if the CSV I posted above works for you as well.

**Comment by SamuelGee** [comment]
Hi Christian, sorry for delayed reply. Somehow Google Takeout creates those CSV files with space before the dash, in those lines with dash ID videos. I replicated today and same glitch had occurred.

Playlist Id,Channel Id,Time Created,Time Updated,Title,Description,Visibility
PL2tOSYRxhz070U_pKKy9S4xJZzHLlVMpL,UCpGMIeOS6v3Nz-oTlS2Ex7Q,2022-04-15 10:31:44 UTC,2022-11-02 08:54:16 UTC,sleep 1,,Private

Video Id,Time Added
jiczBAqku1I,2022-10-12 09:03:50 UTC
_sqYh8puZ-I,2022-10-10 11:26:18 UTC
8L-a1vx_mBw,2022-10-04 14:14:44 UTC
hZsIwDXaN0E,2022-06-18 05:28:26 UTC
 -z77ikRecGI,2022-06-09 19:26:40 UTC
 -hxljpxTaiA,2022-06-09 09:04:26 UTC
1ENkP0h8nAg,2022-06-04 21:58:33 UTC
ifRuWG98ATY,2022-05-26 23:16:37 UTC

**Comment by SamuelGee** [comment]
Github was so nice that he trimmed that space out :DDD
[sleep 1.csv](https://github.com/chrrel/youtube-playlist-exporter/files/9944555/sleep.1.csv)
orig attached

**Comment by chrrel** [comment]
Thanks for the update. I was able to reproduce this issue and will release a version containing a fix. The unnecessary space will now be trimmed automatically. (Additionally, I updated the default server for the default Invidious URL in the config as the previous server does not exist anymore.)
